
version: "3.7"
services:
  mysql-service:
    image: mysql:5.7
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=hrportal
  phpmyadmin:
    depends_on:
      - mysql-service
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8056:80'
    environment:
      PMA_HOST: mysql-service
      MYSQL_ROOT_PASSWORD: test
    networks:
      - spring-boot-mysql-network
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge
